pasarpolis_stackoverflow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from questions import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('login/', views.login),
    path('logout/', views.logout),
    path('articles/', include('questions.urls'), name='articles'),
    path('users/', include('users.urls')),
    path('add_question/', views.add_question),
    path('add_article/', views.add_article),
    path('add_article_backend/', views.add_article_backend),
    path('add_question_backend/', views.add_question_backend),
    path('question_detail/<pk>/upvote_question/', views.upvote_question, name="upvote_question"),
    path('question_detail/<pk>/upvote_comment/<ck>/', views.upvote_comment, name="upvote_comment")
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.contrib import admin
from django.urls import path
from questions import views
app_name = 'articles'

urlpatterns = [
    path('', views.articles_list, name='articles_list'),
    path('articles_detail/<pk>', views.articles_detail, name='articles_detail'),
    path('questions_list', views.questions_list),
    path('create_question/', views.create_question, name="create_question"),
    path('question_detail/<pk>/', views.question_detail, name='question_detail'),
    path('edit_question/<pk>', views.edit_question, name="edit_question"),
    path('search/', views.search, name="search"),
    path('add_question/', views.add_question, name='add_question'),
    path('question_detail/<pk>/post_comment/', views.post_comment, name="post_comment"),
    path('question_detail/<pk>/upvote_question/', views.upvote_question, name="upvote_question"),
    path('question_detail/<pk>/upvote_comment/', views.upvote_comment, name="upvote_comment"),
]

users/urls.py
from django.urls import path, include

from users import views

urlpatterns = [
    path('', views.list_users),
    path('login/', views.login)
]

questions/models.py
from django.db import models
from users.models import User
from markupfield.fields import MarkupField


# Create your models here.


class Content(models.Model):
    title = models.CharField(max_length=500, blank=True)
    body = MarkupField(default_markup_type="html", null=True)
    is_question = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tagging = models.JSONField(default=list)
    upvote = models.IntegerField(default=0, null=True)


class Comment(models.Model):
    question = models.ForeignKey(Content, blank=True, null=True, on_delete=models.SET_NULL)
    comment = MarkupField(default_markup_type="html", null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    upvote = models.IntegerField(default=0, null=True)

questions/forms.py
from django import forms
from . import models


class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Content
        fields = [
            'title', 'body', 'tagging'
        ]

questions/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse_lazy

from questions import forms, models
from questions.models import Content, Comment
from users.models import User


def home(request):
    return render(request, template_name='base.html')


def login(request):
    return render(request, template_name='login.html')


def logout(request):
    try:
        del request.session['user_email']
        del request.session['user_id']
    except:
        return render(request, template_name='login.html')
    return render(request, template_name='login.html')


def articles_detail(request, pk):
    article = Content.objects.get(id=pk)
    comments = Comment.objects.filter(question_id=article.id)
    con_obj = Content.objects.get(id=article.id)
    return render(request, template_name='article_detail.html', context={"article": article,
                                                                         'comments': comments,
                                                                         'upvote': con_obj.upvote})


def questions(request):
    return render(request, template_name='questions.html')


def add_question(request):
    return render(request, template_name='add_question.html')


def add_article(request):
    return render(request, template_name='add_article.html')


def add_question_backend(request):
    content_title = request.POST['title']
    content_description = request.POST['description']
    content_tags = [request.POST['tags']]
    content = Content.objects.create(title=content_title, body=content_description, tagging=content_tags,
                                     is_question=True)
    content.author_id = request.session.get("user_id")
    content.save()
    return redirect(f'/articles/question_detail/{content.id}/', content={"question": content})


def add_article_backend(request):
    content_title = request.POST['title']
    content_description = request.POST['description']
    content_tags = [request.POST['tags']]
    content = Content.objects.create(title=content_title, body=content_description, tagging=content_tags, )
    content.author_id = request.session.get("user_id")
    content.save()
    return redirect(f'/articles/articles_detail/{content.id}', content={"article": content})


def articles_list(request):
    _articles = Content.objects.filter(is_question=False)
    print("logged in user email", request.session.get("user_email"))
    return render(request, template_name='articles.html', context={'articles': _articles})


def questions_list(request):
    _articles = Content.objects.filter(is_question=True)
    print("logged in user email", request.session.get("user_email"))
    return render(request, template_name='question_list.html', context={'questions': _articles})


def question_detail(request, pk):
    question = get_object_or_404(Content, pk=pk)
    comments = Comment.objects.filter(question_id=question.id)
    con_obj = Content.objects.get(id=question.id)
    print("Comment values are", comments)
    print("content obj is", con_obj.id)
    print("content obj upvote is", con_obj.upvote)
    return render(request, 'question_detail.html',
                  context={'question': question, 'comments': comments, 'upvote': con_obj.upvote})


@login_required
def create_question(request):
    form = forms.QuestionForm()
    if request.method == "POST":
        form = forms.QuestionForm(request.POST)
        if form.is_valid:
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            messages.success(request, "Question created successfully")
            return HttpResponseRedirect(reverse_lazy('questions:question_detail', kwargs={'pk': question.pk}))
    return render(request, 'question_form.html', {'form': form})


@login_required
def edit_question(request, pk):
    question = get_object_or_404(Content, pk=pk)
    form_class = forms.QuestionForm
    form = form_class(instance=question)
    if request.method == "POST":
        form = form_class(request.POST, instance=question)
        if form.is_valid:
            form.save()
            messages.success(request, "Question updated successfully")
            return HttpResponseRedirect(reverse_lazy('questions:question_detail', kwargs={'pk': question.pk}))
    return render(request, 'question_form.html', {
        'form': form,
        'question': question
    })


def search(request):
    search_k = request.POST["search"]
    results = Content.objects.filter(title__icontains=search_k)
    return render(request, template_name='search.html', context={'questions': results})


def post_comment(request, pk):
    print("Hello there")
    question = get_object_or_404(Content, pk=pk)
    comment_content = request.POST['comment']
    user = request.session["user_id"]
    # user_mail = User.object.filter(id = user)
    print(comment_content)
    print(question.id)
    print(user)
    fields = Comment._meta.get_fields()
    print(fields)
    a = Comment(question_id=question.id, comment=comment_content, author_id=user)
    a.save()
    if question.is_question:
        return redirect(f'/articles/question_detail/{pk}/', content={"question": question})
    else:
        return redirect(f'/articles/articles_detail/{pk}', content={"article": question})



def upvote_question(request, pk):
    print('inside upvote_question api')
    user_id = request.session["user_id"]
    print("user id is", user_id)
    user = get_object_or_404(User, pk=user_id)
    print("user is", user, type(user))
    question = get_object_or_404(Content, pk=pk)
    print("question is", question, type(question))
    user_upvote_increase = User.objects.get(id = question.author.id)
    print("User to upvote is", user_upvote_increase.id)
    if user_id != question.author:
        question.upvote = question.upvote + 1
        question.save()
        # question.update(upvote=question.upvote+1)
        # user.update(points=user.points+1)
        user_upvote_increase.points = user_upvote_increase.points + 1
        user_upvote_increase.save()
    comments = Comment.objects.filter(question_id=question.id)
    con_obj = Content.objects.get(id=question.id)

    # print("Comment values are", comments)
    if question.is_question:
        return render(request, 'question_detail.html',
                  context={'question': question, 'comments': comments, 'upvote': con_obj.upvote})
    else:
        return render(request, 'articles_detail.html',
                  context={'article': question, 'comments': comments, 'upvote': con_obj.upvote})
    # question_detail(pk = pk)
    # return render(request, template_name='question_detail.html', context={"question": question})


def upvote_comment(request, pk, ck):
    user_id = request.session["user_id"]
    user = get_object_or_404(User, pk=user_id)
    comment = get_object_or_404(Comment, pk=ck)
    question = get_object_or_404(Content, pk=pk)
    user_upvote_increase = User.objects.get(id = comment.author.id)
    if user_id != comment.author.id:
        # print('User comment upvote inside else if', comment.upvote)
        comment.upvote = comment.upvote + 1
        comment.save()
        # User.update(points=User.points + 1)
        
        user_upvote_increase.points += 1

        user_upvote_increase.save()
    comments = Comment.objects.filter(question_id=question.id)
    # print('User comment upvote is', comment.upvote)
    if question.is_question:
        return redirect(f'/articles/question_detail/{question.id}', context={'question': question, 'comments': comments,
                                                                             'upvote': question.upvote})
    else:
        return redirect(f'/articles/articles_detail/{question.id}', context={'article': question, 'comments': comments,
                                                                            'upvote': question.upvote})

    # return render(request, template_name='article_detail.html', context={"article": question})

templates/add_article.html
{% extends 'base.html'%}
{% block content %}


<script>
function fun()
{
	var question = document.getElementById("question").value;
    var description = documnent.getElementById("description").value;
    var tag = documnent.getElementById("tag").value;

	if(!question)
	{
		alert("all fields are required");
	}

}



</script>
<!-- <link href="/templates/add_question.css" rel="stylesheet"> -->
<!--<link type="text/css" href="/assets/css/add_question.css" rel="stylesheet"/>-->

<div class="container-fluid">
    <div class="row middle">
        <div class="col-md-12">
            <form method="post" role="form" action="/add_article_backend/">
				{% csrf_token %}
                <div class="form-group">
                    <input type="text" required class="form-control" style="height:50px" name="title" placeholder="Title"/>
                </div>
                <div class="form-group">
                    <textarea class="form-control bcontent" style="height:400px" required name="description"
                              placeholder="Description"></textarea>
                </div>
                <div class="form-group">
                    <textarea class="form-control bcontent" name="tags" required placeholder="Tags"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" name="Submit" value="Publish" class="btn btn-primary form-control"/>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

templates/add_question.html
{% extends 'base.html'%}
{% block content %}


<script>
function fun()
{
	var question = document.getElementById("question").value;
    var description = documnent.getElementById("description").value;
    var tag = documnent.getElementById("tag").value;

	if(!question)
	{
		alert("all fields are required");
	}

}



</script>
<!-- <link href="/templates/add_question.css" rel="stylesheet"> -->
<!--<link type="text/css" href="/assets/css/add_question.css" rel="stylesheet"/>-->

<div class="container-fluid">
    <div class="row middle">
        <div class="col-md-12">
            <form method="post" role="form" action="/add_question_backend/">
				{% csrf_token %}
                <div class="form-group">
                    <input type="text" required class="form-control" style="height:50px" name="title" placeholder="Title"/>
                </div>
                <div class="form-group">
                    <textarea class="form-control bcontent" style="height:400px" required name="description"
                              placeholder="Description"></textarea>
                </div>
                <div class="form-group">
                    <textarea class="form-control bcontent" name="tags" required placeholder="Tags"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" name="Submit" value="Publish" class="btn btn-primary form-control"/>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

templates/article_detail.html
{% extends 'base.html'%}
{% block content %}


<style>
</style>
<head>
    <link type="text/css" href="/assets/css/article_detail.css" rel="stylesheet"/>
</head>

<br>
<div class="container-fluid">
    <div class="depname">
        <div class ='article_title'>
            <h2>
                {{ article.title }}
            </h2>
        </div>
        <div>
            <p>
                {{ article.body }}
            </p>
        </div>
        <div>
            <div class ='article_by'>
                <h5>
                    By: {{ article.author }}
                    on {{ article.created_at|date:"j F, Y" }}
                </h5>
            </div>
        </div>
        <div class="logo_box">
            <form method="POST" action="/articles/question_detail/{{article.id}}/upvote_question/">
                {% csrf_token %}
                <h2 class="count">{{upvote}}</h2>
                <button type="submit"> <img src="/assets/images/thumb__up.jpeg" height ="70" width="70" /></button>
            </form>
        </div>
    </div>
</div>


<script>
    function call_comment_api(user_id)
    {
        var user_id = user_id;
        if(!user_id)
        {
            alert("login required");
            location.href('/login')
        }
    }



</script>
<br>

<div class="container-fluid">
    <div class = "post_your_comment">
        <form method="POST" action="/articles/question_detail/{{article.id}}/post_comment/">
            {% csrf_token %}
            <!-- {{ comment_form.as_p }} -->
            <h3 class = "comment_title">Post your Comment here:</h3> <br>
            <textarea width=200px name="comment" required id="comment" placeholder="Comment for the content"></textarea><br>
            <b><input type="submit" name="post_comment" onclick="call_comment_api('{{request.session.user_id}}');"
                   value="POST"></b>

        </form>

    </div>

    <h2 class ='comment_list_title'>COMMENTS</h2>
    <div class="comment_list">
        {% for comment in comments %}

        <div>
            <hr>
            {% if comment.comment|wordcount <= 30 %}
            <h4>{{ comment.comment }}</h4>
            {% else %}
            <h4>{{ comment.comment|truncatewords:30 }}</h4>
            {% endif %}
        </div>
        <div class="author_by">By: {{ comment.author.email }}
            on {{ comment.created_at|date:"j F, Y" }}
        </div>
        <div class="logo_box">
            <form method="POST" action="/question_detail/{{article.id}}/upvote_comment/{{comment.id}}/">
                {% csrf_token %}
                <h4>{{comment.upvote}}</h4>
                <button type="submit"> <img src="/assets/images/thumb__up.jpeg" height ="50" width="50" /></button>
            </form>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

templates/articles.html
{% extends 'base.html'%}
{% block content %}
{%  for article in articles %}
<br>
<head>
    <link type="text/css" href="/assets/css/articles.css" rel="stylesheet"/>
</head>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10">
            <div class="depname">
                <div class="article_title">
                    <a class="text-info card-title responsive-font-size h5"
                    href="{% url 'articles:articles_detail' pk=article.pk %}">
                    {{ article.title }}</a>
                <hr>
                {% if article.body|wordcount <= 30 %}
                <p class="card-text">{{ article.body }}</p>
                {% else %}
                    {{ article.body|truncatewords:30 }}
                    <a href="{% url 'articles:articles_detail' pk=article.pk %}" class="card-link">Read More</a>
                {% endif %}
                </div>
                <div>By: {{ article.author }}
                            - {{ article.created_at|date:"j F, Y" }}</div>
                </div>
            </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <link type="text/css" href="/assets/css/bootstrap.min.css" rel="stylesheet"/>
    <link type="text/css" href="/assets/css/sty.css" rel="stylesheet"/>
    <!-- <link href="https://fonts.googleapis.com/css?family=Lato:300i,400,700,900,900i" rel="stylesheet"> -->

    <style>
* {
  box-sizing: border-box;
}

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 5px;
  height: 100%;
  }

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
form.example input[type=text] {
  padding: 10px;
  font-size: 17px;
  border: 1px solid grey;
  float: left;
  width: 80%;
  background: #f1f1f1;
}

form.example button {
  float: left;
  width: 20%;
  padding: 10px;
  background: #2196F3;
  color: white;
  font-size: 17px;
  border: 1px solid grey;
  border-left: none;
  cursor: pointer;
}

form.example button:hover {
  background: #0b7dda;
}

form.example::after {
  content: "";
  clear: both;
  display: table;
}


    </style>

</head>
<body>


<nav class="navbar navbar-default m">
    <div class="container-fluid top-bar">
        <div class="row ">
            <div class="col-sm-12">
                <h1 style="text-align:center;">
                    <b><a href="/">PASARPOLIS ASKTOPIA</a></b>
                </h1>
            </div>

        </div>
    </div>
    <div class="container-fluid nav-bar">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <a href="/"><li>HOME</li></a>
                <a href="/articles"><li>ARTICLES</li></a>
                <a href="/articles/questions_list"><li>QUESTIONS</li></a>
                <a href="/users/"><li>TOP USERS</li></a>
                <!-- <a href="/add_question"></li>ADD QUESTION</li></a> -->
                {% if request.session.user_email %}
                <a href="/logout"><li style="margin-left:400px">LOGOUT</li></a>
                    <li><img src="{{request.session.user_profile_pic}}" alt="Avatar" width="40" height="40px"></li>
                {% else %}
                <a href="/login"><li style="margin-left:500px">LOGIN</li></a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}

<div class="main_section_body">
    <div class="container-fluid">
        <div class = "row">
            <div class="col-md-10 search_bar">
                <!-- Load icon library -->
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
                <!-- The form -->
                <form class="example" action="/articles/search/" method="post">
                    {% csrf_token %}
                    <input type="text" placeholder="Search.." name="search">
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
        </div>
    </div>

    <!-- <div style="margin: 20px"></div> -->

    <div class="container-fluid">
        <div class = "row">
            <div class="col-md-5 first_section">
                <h2 style="font-family: Lato;">A private platform building the definitive collection of coding questions & answers</h2>
                <p>Browse through the knowledge base of entire Pasarpolis community and what they have got to say to you.
                    This catalog of articles contains ideas and implementations from across teams and projects is all available and accessible to everyone.
                    Follow authors and topics to stay updated.
                </p>
                <button onclick="create_article()">Create Article</button>
            </div>
            <div class="col-md-1 centre_section"></div>
            <div class="col-md-5 second_section">
                <h2 style="font-family: Lato;">A collaboration & knowledge sharing SaaS platform for Pasarpolis </h2>
                <p>The question and answer site designed to help people, to help each other: To ask, to learn, to share and to grow. Let community trust you more by earning points while asking questions and answering them.
                    Improve your productivity by not solving already solved technical problems and concentrate more on the use cases.
                </p>
                <button onclick="ask_question()">Ask Question</button>
            </div>
        </div>
    </div>

</div>


{% endblock content %}


<div class="container-fluid">
    <footer class="sticky-footer">
        <div class="row">
            <div class="col-sm-4">
                <h4>ABOUT PASARPOLIS</h4>
                <p style="font-size:12px">Established in 2015, PasarPolis is Southeast Asia’s largest Insurance Technology
                    (insurtech) platform. PasarPolis’ mission is to redefine insurance so that it can be accessed more
                    easily, quickly, and on target by utilizing the latest technology. PasarPolis’ technology ensures a
                    seamless consumer experience from product selection to claims. After over six years, PasarPolis has
                    become one of the insurtech industry leaders in Indonesia with a focus on affordable insurance products.
                    PasarPolis has also invoked national pride after it started operations in Thailand and Vietnam.</p>
            </div>
            <div class="col-sm-4">
                <h4>INFORMATION</h4>
                <ul class="text-small others-list">
                    <li><a class="footer__link" href="https://pasarpolis.io/blogs">Blog</a>
                    </li>
                    <li><a class="footer__link" href="https://pasarpolis.io/news">Press Release</a></li>
                    <li><a class="footer__link" href="/claim">Submit Claim</a></li>
                    <li><a class="footer__link" href="/faq">FAQ</a></li>
                    <li><a class="footer__link" href="https://pasarpolis.io/dictionary">Insurance Dictionary</a></li>
                    <li><a class="footer__link" href="https://developers.pasarpolis.io/">Developer</a></li>
                </ul>
            </div>
            <div class="col-sm-4">
                <h4>OUR OFFICES</h4>
                <p>Indonesia</p>
                <p>One Pacific Place, 10th Floor unit D-H
                    SCBD Jl. Jend. Sudirman Kav 52-53
                    Jakarta Selatan 12190</p>
                <p>
                    P : 021 5086 0658 (One Pacific)
                    P : 021 3111 8178 (One Pacific)
                    P : 021 5086 0657 (Tifa Building)
                    P : 021 3111 8177 (Tifa Building)
                    E : cs@pasarpolis.com

                    Customer Care
                    P : 021 5089 0580
                    W : 0877 0017 8000
                </p>
                <div class="container">
                    <a target="_blank" class="footer__link social-link" href="https://www.instagram.com/pasarpolis/"><img src="https://storage.googleapis.com/pp_img/website/pasarpolis/social-media/instagram.png"></a>
                    <a target="_blank" class="footer__link social-link" href="https://www.facebook.com/pasarpolis/"><img src="https://storage.googleapis.com/pp_img/website/pasarpolis/social-media/facebook.png"></a>
                    <a target="_blank" class="footer__link social-link" href="https://twitter.com/pasarpolis"><img src="https://storage.googleapis.com/pp_img/website/pasarpolis/social-media/twitter.png"></a>
                    <a target="_blank" class="footer__link social-link" href="https://www.youtube.com/channel/UC5wZUL4FVGQSfQYJ8cWQQ1Q"><img src="https://storage.googleapis.com/pp_img/website/pasarpolis/social-media/youtube.png"></a></div>
            </div>
        </div>
    </footer>
</div>
<script>
    function ask_question(){
    location.href ="/add_question"
    }
    function create_article(){
    location.href ="/add_article"
    }

</script>


<script type="text/javascript" src="/assets/js/jquery1.js">

</script>
<script type="text/javascript" src="/assets/js/bootstrap.min.js">
</script>
</body>
</html>

templates/question_list.html
{% extends 'base.html'%}
{% block content %}
{%  for question in questions %}
<br>
<head>
    <link type="text/css" href="/assets/css/question_list.css" rel="stylesheet"/>
</head>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10">
            <div class="depname">
                <div class="question_title">
                        <a class="text-info card-title responsive-font-size h5"
                        href="{% url 'articles:question_detail' pk=question.pk %}">
                        {{ question.title }}</a>
                    <hr>
                </div>
                <div>
                    {% if question.body|wordcount <= 30 %}
                    <p class="card-text">{{ question.body }}</p>
                    {% else %}
                        {{ question.body|truncatewords:30 }}
                        <a href="{% url 'articles:question_detail' pk=question.pk %}" class="card-link">Read More</a>
                    {% endif %}
                </div>
                <div>By: {{ question.author }}
                            - {{ question.created_at|date:"j F, Y" }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

templates/questions.html
{% extends 'base.html'%}
{% block content %}
<div class="container-fluid middle">
    <div class="row">
        <div class="col-sm-4">

        </div>
        <div class="col-sm-8">
            <img src="/assets/images/w.jpg" style="height:500px;">
        </div>
    </div>
</div>

{% endblock content %}

templates/search.html
{% extends 'base.html'%}
{% block content %}
{%  for question in questions %}
<br>
<div class="card my-6 border-info">
    <div class="depname">
        <div>

            <a class="text-info card-title responsive-font-size h5"
            href="{% url 'articles:question_detail' pk=question.pk %}">
            {{ question.title }}</a>

        <hr>
        {% if question.body|wordcount <= 30 %}
        <p class="card-text">{{ question.body }}</p>
        {% else %}
            {{ question.body|truncatewords:30 }}
            <a href="{% url 'articles:question_detail' pk=question.pk %}" class="card-link">Read More</a>
        {% endif %}
    </div>
        <div>By: {{ question.author }}
                    - {{ question.created_at|date:"j F, Y" }}</div>
    </div>
</div>
{% endfor %}

{% endblock content %}

templates/users_list.html
{% extends 'base.html'%}
{% block content %}
<ol reversed>
{%  for user in users  %}
<br>
<head>
    <link type="text/css" href="/assets/css/user_list.css" rel="stylesheet"/>
</head>

<div class="container-fluid">
    <div class="depname" style="background-color:rgba(230, 169, 15, 0.599);">
        <div class="row">
            <div class="col-sm-3">
                <img src="/media/documents/user-login.png" alt="Trulli" width="100" height="100" style="margin-top:20px;">
            </div>
            <div class="col-sm-3">
                <h4> Name : {{user.name}} </h4>
                <h4>Email : {{user.email}}</h4>
                <h4> Active Since : {{user.date_joined|date:"j F, Y" }}</h4>
                <h4>Score : {{user.score}}</h4>
            </div>
            <div class="col-sm-6 href">
                <h4>Contribution </h4>
                <ul>
                {% for article in user.articles %}
                    <li><a href="{% url 'articles:articles_detail' pk=article.pk %}">{{ article.title }}</a></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endfor %}
</ol>

{% endblock content %}